# Generated by Django 4.2.29 on 2026-05-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
