# Generated by Django 4.2.27 on 2026-03-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tarjeta_credito', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_registro', models.DateField()),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente')], max_length=10)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
