# Generated by Django 4.2.29 on 2026-05-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
